### ISSUE TITLE
Add support for resources and attributes

### ISSUE THREAD

**Issue by DavidWittman** [AnsibleShipyard/ansible-mesos#40]
It'd be nice to provide support for configuring [resources/attributes](https://mesos.apache.org/documentation/attributes-resources/) within Mesos using this role. The `mesos-init-wrapper` reads these values from `/etc/mesos-slave/attributes/X` and `/etc/mesos-slave/resources/X` where `X` is the name of the resource or attribute.

I think two new dicts should do the trick:

``` yaml
mesos_attributes:
  rack_id: 1
  os: centos7

mesos_resources:
  ports: "[21000-22000,31000-32000]"
```

I'll be happy to add these changes in; just thought I'd open an issue first to track the changes and request comments or suggestions.

**Comment by JasonGiedymin** [comment]
Sounds good though what about using resource.txt via a template instead?

-Jason

**Comment by jolexa** [comment]
I've thought about adding this feature as well and couldn't wrap my head around a sane way to specify resources specific to a role.

**Comment by DavidWittman** [comment]
@JasonGiedymin Good point re: `/etc/mesos-slave/resources` and `/etc/mesos-slave/attributes`. That'll be easier than managing the individual files.

@jolexa I guess when roles are taken into consideration, it may make more sense to store the resources as follows:

``` yaml
mesos_resources:
  - name: ports(*)
    value: "[21000-22000,31000-32000]"
  - name: ports(public)
    value: "[8000-9000]"
```

**Comment by jolexa** [comment]
That does make sense to me.

**Comment by DavidWittman** [comment]
@jolexa It turns out that YAML accepts parenthesis and asterisks as key names, so I just kept `mesos_resources` as a dictionary. The example provided above looks like this now:

``` yaml
mesos_resources:
  ports(*): "[21000-22000,31000-32000]"
  ports(public): "[8000-9000]"

**Comment by ernestas-poskus** [comment]
@DavidWittman does this https://github.com/AnsibleShipyard/ansible-mesos/pull/56 solve your issue ? If so pleas close

**Comment by DavidWittman** [comment]
@ernestas-poskus I don't believe so. As far as I know, the only way to set resources and attributes is by defining them in `/etc/mesos-slave/resources` and `/etc/mesos-slave/attributes`. I don't think it's possible to set them via environment variables, which is what #56 does.

If that's incorrect, let me know. Otherwise I'll need to address some of the issues brought up in my PR.

**Comment by veger** [comment]
Works for me:
```
    mesos_slave_additional_configs:
    - name: ATTRIBUTES
      value: '"rack:internal"'
    - name: RESOURCES
      value: '"ports:[ 31000-32000]"'
```
