### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by akhld** [AnsibleShipyard/ansible-mesos#50]
Couple of things are missing from the documentation:
- Instruction to run the project
- What to expect when you run it

Can someone post screenshots or execution command of the same?

**Comment by ernestas-poskus** [comment]
@akhld 

Here is sample settings to run role. For Mesos to run you need Zookeeper and Zookpers requires JAVA.

```yaml
- name: Zookeeper + Mesos [master-slave]
  hosts: all
  sudo: yes
  roles:
    - role: ansible-java
      java_packages:
        - java-1.8.0-openjdk

    - role: ansible-zookeeper
      zookeeper_version: 3.4.8
      zookeeper_url: http://www.eu.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz

    - role: ansible-mesos
      mesos_install_mode: master-slave
      mesos_ip: 127.0.0.1
      mesos_version: '0.28.1'
      mesos_containerizers: 'docker,mesos'
```

> What to expect when you run it

this is the question you have to answer yourself, because it depends what you need.
